# Makefile.in generated by automake 1.18.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2025 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
am__rm_f = rm -f $(am__rm_f_notfound)
am__rm_rf = rm -rf $(am__rm_f_notfound)
pkgdatadir = $(datadir)/75fasmod
pkgincludedir = $(includedir)/75fasmod
pkglibdir = $(libdir)/75fasmod
pkglibexecdir = $(libexecdir)/75fasmod
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = 75fasmod$(EXEEXT)
check_PROGRAMS = test_frequency$(EXEEXT) test_power$(EXEEXT) \
	test_vfo$(EXEEXT) test_tnc$(EXEEXT) test_single_dual$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES = Doxyfile
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_75fasmod_OBJECTS = src/75fasmod-main.$(OBJEXT) \
	src/75fasmod-DataSocket.$(OBJEXT) src/75fasmod-cobs.$(OBJEXT) \
	src/75fasmod-Frame.$(OBJEXT) \
	src/75fasmod-RadioController.$(OBJEXT) \
	src/75fasmod-THD75.$(OBJEXT) src/75fasmod-ModemDSP.$(OBJEXT) \
	src/75fasmod-TcmConfig.$(OBJEXT)
75fasmod_OBJECTS = $(am_75fasmod_OBJECTS)
am__DEPENDENCIES_1 =
75fasmod_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
75fasmod_LINK = $(CXXLD) $(75fasmod_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
am_test_frequency_OBJECTS = test/frequency-test_frequency.$(OBJEXT) \
	src/test_frequency-RadioController.$(OBJEXT) \
	src/test_frequency-THD75.$(OBJEXT)
test_frequency_OBJECTS = $(am_test_frequency_OBJECTS)
test_frequency_DEPENDENCIES = $(am__DEPENDENCIES_1)
am_test_power_OBJECTS = test/power-test_power.$(OBJEXT) \
	src/test_power-RadioController.$(OBJEXT) \
	src/test_power-THD75.$(OBJEXT)
test_power_OBJECTS = $(am_test_power_OBJECTS)
test_power_DEPENDENCIES = $(am__DEPENDENCIES_1)
am_test_single_dual_OBJECTS =  \
	test/single_dual-test_single_dual.$(OBJEXT) \
	src/test_single_dual-RadioController.$(OBJEXT) \
	src/test_single_dual-THD75.$(OBJEXT)
test_single_dual_OBJECTS = $(am_test_single_dual_OBJECTS)
test_single_dual_DEPENDENCIES = $(am__DEPENDENCIES_1)
am_test_tnc_OBJECTS = test/tnc-test_tnc.$(OBJEXT) \
	src/test_tnc-RadioController.$(OBJEXT) \
	src/test_tnc-THD75.$(OBJEXT)
test_tnc_OBJECTS = $(am_test_tnc_OBJECTS)
test_tnc_DEPENDENCIES = $(am__DEPENDENCIES_1)
am_test_vfo_OBJECTS = test/vfo-test_vfo.$(OBJEXT) \
	src/test_vfo-RadioController.$(OBJEXT) \
	src/test_vfo-THD75.$(OBJEXT)
test_vfo_OBJECTS = $(am_test_vfo_OBJECTS)
test_vfo_DEPENDENCIES = $(am__DEPENDENCIES_1)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/$(DEPDIR)/75fasmod-DataSocket.Po \
	src/$(DEPDIR)/75fasmod-Frame.Po \
	src/$(DEPDIR)/75fasmod-ModemDSP.Po \
	src/$(DEPDIR)/75fasmod-RadioController.Po \
	src/$(DEPDIR)/75fasmod-THD75.Po \
	src/$(DEPDIR)/75fasmod-TcmConfig.Po \
	src/$(DEPDIR)/75fasmod-cobs.Po src/$(DEPDIR)/75fasmod-main.Po \
	src/$(DEPDIR)/test_frequency-RadioController.Po \
	src/$(DEPDIR)/test_frequency-THD75.Po \
	src/$(DEPDIR)/test_power-RadioController.Po \
	src/$(DEPDIR)/test_power-THD75.Po \
	src/$(DEPDIR)/test_single_dual-RadioController.Po \
	src/$(DEPDIR)/test_single_dual-THD75.Po \
	src/$(DEPDIR)/test_tnc-RadioController.Po \
	src/$(DEPDIR)/test_tnc-THD75.Po \
	src/$(DEPDIR)/test_vfo-RadioController.Po \
	src/$(DEPDIR)/test_vfo-THD75.Po \
	test/$(DEPDIR)/frequency-test_frequency.Po \
	test/$(DEPDIR)/power-test_power.Po \
	test/$(DEPDIR)/single_dual-test_single_dual.Po \
	test/$(DEPDIR)/tnc-test_tnc.Po test/$(DEPDIR)/vfo-test_vfo.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(75fasmod_SOURCES) $(test_frequency_SOURCES) \
	$(test_power_SOURCES) $(test_single_dual_SOURCES) \
	$(test_tnc_SOURCES) $(test_vfo_SOURCES)
DIST_SOURCES = $(75fasmod_SOURCES) $(test_frequency_SOURCES) \
	$(test_power_SOURCES) $(test_single_dual_SOURCES) \
	$(test_tnc_SOURCES) $(test_vfo_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
AM_RECURSIVE_TARGETS = cscope check recheck
am__tty_colors_dummy = \
  mgn= red= grn= lgn= blu= brg= std=; \
  am__color_tests=no
am__tty_colors = { \
  $(am__tty_colors_dummy); \
  if test "X$(AM_COLOR_TESTS)" = Xno; then \
    am__color_tests=no; \
  elif test "X$(AM_COLOR_TESTS)" = Xalways; then \
    am__color_tests=yes; \
  elif test "X$$TERM" != Xdumb && { test -t 1; } 2>/dev/null; then \
    am__color_tests=yes; \
  fi; \
  if test $$am__color_tests = yes; then \
    red='[0;31m'; \
    grn='[0;32m'; \
    lgn='[1;32m'; \
    blu='[1;34m'; \
    mgn='[0;35m'; \
    brg='[1m'; \
    std='[m'; \
  fi; \
}
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
  || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
       $(am__cd) "$$dir" && echo $$files | $(am__xargs_n) 40 $(am__rm_f); }; \
  }
am__recheck_rx = ^[ 	]*:recheck:[ 	]*
am__global_test_result_rx = ^[ 	]*:global-test-result:[ 	]*
am__copy_in_global_log_rx = ^[ 	]*:copy-in-global-log:[ 	]*
# A command that, given a newline-separated list of test names on the
# standard input, print the name of the tests that are to be re-run
# upon "make recheck".
am__list_recheck_tests = $(AWK) '{ \
  recheck = 1; \
  while ((rc = (getline line < ($$0 ".trs"))) != 0) \
    { \
      if (rc < 0) \
        { \
          if ((getline line2 < ($$0 ".log")) < 0) \
	    recheck = 0; \
          break; \
        } \
      else if (line ~ /$(am__recheck_rx)[nN][Oo]/) \
        { \
          recheck = 0; \
          break; \
        } \
      else if (line ~ /$(am__recheck_rx)[yY][eE][sS]/) \
        { \
          break; \
        } \
    }; \
  if (recheck) \
    print $$0; \
  close ($$0 ".trs"); \
  close ($$0 ".log"); \
}'
# A command that, given a newline-separated list of test names on the
# standard input, create the global log from their .trs and .log files.
am__create_global_log = $(AWK) ' \
function fatal(msg) \
{ \
  print "fatal: making $@: " msg | "cat >&2"; \
  exit 1; \
} \
function rst_section(header) \
{ \
  print header; \
  len = length(header); \
  for (i = 1; i <= len; i = i + 1) \
    printf "="; \
  printf "\n\n"; \
} \
{ \
  copy_in_global_log = 1; \
  global_test_result = "RUN"; \
  while ((rc = (getline line < ($$0 ".trs"))) != 0) \
    { \
      if (rc < 0) \
         fatal("failed to read from " $$0 ".trs"); \
      if (line ~ /$(am__global_test_result_rx)/) \
        { \
          sub("$(am__global_test_result_rx)", "", line); \
          sub("[ 	]*$$", "", line); \
          global_test_result = line; \
        } \
      else if (line ~ /$(am__copy_in_global_log_rx)[nN][oO]/) \
        copy_in_global_log = 0; \
    }; \
  if (copy_in_global_log) \
    { \
      rst_section(global_test_result ": " $$0); \
      while ((rc = (getline line < ($$0 ".log"))) != 0) \
      { \
        if (rc < 0) \
          fatal("failed to read from " $$0 ".log"); \
        print line; \
      }; \
      printf "\n"; \
    }; \
  close ($$0 ".trs"); \
  close ($$0 ".log"); \
}'
# Restructured Text title.
am__rst_title = { sed 's/.*/   &   /;h;s/./=/g;p;x;s/ *$$//;p;g' && echo; }
# Solaris 10 'make', and several other traditional 'make' implementations,
# pass "-e" to $(SHELL), and POSIX 2008 even requires this.  Work around it
# by disabling -e (using the XSI extension "set +e") if it's set.
am__sh_e_setup = case $$- in *e*) set +e;; esac
# Default flags passed to test drivers.
am__common_driver_flags = \
  --color-tests "$$am__color_tests" \
  $$am__collect_skipped_logs \
  --enable-hard-errors "$$am__enable_hard_errors" \
  --expect-failure "$$am__expect_failure"
# To be inserted before the command running the test.  Creates the
# directory for the log if needed.  Stores in $dir the directory
# containing $f, in $tst the test, in $log the log.  Executes the
# developer-defined test setup AM_TESTS_ENVIRONMENT (if any), and
# passes TESTS_ENVIRONMENT.  Set up options for the wrapper that
# will run the test scripts (or their associated LOG_COMPILER, if
# thy have one).
am__check_pre = \
$(am__sh_e_setup);					\
$(am__vpath_adj_setup) $(am__vpath_adj)			\
$(am__tty_colors);					\
srcdir=$(srcdir); export srcdir;			\
case "$@" in						\
  */*) am__odir=`echo "./$@" | sed 's|/[^/]*$$||'`;;	\
    *) am__odir=.;; 					\
esac;							\
test "x$$am__odir" = x"." || test -d "$$am__odir" 	\
  || $(MKDIR_P) "$$am__odir" || exit $$?;		\
if test -f "./$$f"; then dir=./;			\
elif test -f "$$f"; then dir=;				\
else dir="$(srcdir)/"; fi;				\
tst=$$dir$$f; log='$@'; 				\
if test -n '$(IGNORE_SKIPPED_LOGS)'; then		\
  am__collect_skipped_logs='--collect-skipped-logs no';	\
else							\
  am__collect_skipped_logs='';				\
fi;							\
if test -n '$(DISABLE_HARD_ERRORS)'; then		\
  am__enable_hard_errors=no; 				\
else							\
  am__enable_hard_errors=yes; 				\
fi; 							\
case " $(XFAIL_TESTS) " in				\
  *[\ \	]$$f[\ \	]* | *[\ \	]$$dir$$f[\ \	]*) \
    am__expect_failure=yes;;				\
  *)							\
    am__expect_failure=no;;				\
esac; 							\
$(AM_TESTS_ENVIRONMENT) $(TESTS_ENVIRONMENT)
# A shell command to get the names of the tests scripts with any registered
# extension removed (i.e., equivalently, the names of the test logs, with
# the '.log' extension removed).  The result is saved in the shell variable
# '$bases'.  This honors runtime overriding of TESTS and TEST_LOGS.  Sadly,
# we cannot use something simpler, involving e.g., "$(TEST_LOGS:.log=)",
# since that might cause problem with VPATH rewrites for suffix-less tests.
# See also 'test-harness-vpath-rewrite.sh' and 'test-trs-basic.sh'.
am__set_TESTS_bases = \
  bases='$(TEST_LOGS)'; \
  bases=`for i in $$bases; do echo $$i; done | sed 's/\.log$$//'`; \
  bases=`echo $$bases`
AM_TESTSUITE_SUMMARY_HEADER = ' for $(PACKAGE_STRING)'
RECHECK_LOGS = $(TEST_LOGS)
TEST_SUITE_LOG = test-suite.log
TEST_EXTENSIONS =  .test
LOG_DRIVER = $(SHELL) $(top_srcdir)/test-driver
LOG_COMPILE = $(LOG_COMPILER) $(AM_LOG_FLAGS) $(LOG_FLAGS)
am__set_b = \
  case '$@' in \
    */*) \
      case '$*' in \
        */*) b='$*';; \
          *) b=`echo '$@' | sed 's/\.log$$//'`; \
       esac;; \
    *) \
      b='$*';; \
  esac
am__test_logs1 = $(TESTS:=.log)
am__test_logs2 = $(am__test_logs1:.log=.log)
TEST_LOGS = $(am__test_logs2:.test.log=.log)
TEST_LOG_DRIVER = $(SHELL) $(top_srcdir)/test-driver
TEST_LOG_COMPILE = $(TEST_LOG_COMPILER) $(AM_TEST_LOG_FLAGS) \
	$(TEST_LOG_FLAGS)
am__DIST_COMMON = $(srcdir)/Doxyfile.in $(srcdir)/Makefile.in COPYING \
	INSTALL README.md ar-lib compile depcomp install-sh missing \
	test-driver
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -700 -exec chmod u+rwx {} ';' \
      ; rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = -9
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = \
  find . \( -type f -a \! \
            \( -name .nfs* -o -name .smb* -o -name .__afs* \) \) -print
ACLOCAL = ${SHELL} '/home/woodard/src/75fasmod/missing' aclocal-1.18
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} '/home/woodard/src/75fasmod/missing' autoconf
AUTOHEADER = ${SHELL} '/home/woodard/src/75fasmod/missing' autoheader
AUTOMAKE = ${SHELL} '/home/woodard/src/75fasmod/missing' automake-1.18
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -std=c++20
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"75fasmod\" -DPACKAGE_TARNAME=\"75fasmod\" -DPACKAGE_VERSION=\"0.1.0\" -DPACKAGE_STRING=\"75fasmod\ 0.1.0\" -DPACKAGE_BUGREPORT=\"your.email@example.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"75fasmod\" -DVERSION=\"0.1.0\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ETAGS = etags
EXEEXT = 
FMT_CFLAGS = 
FMT_LIBS = -lfmt
GNURADIO_CFLAGS = -I/home/woodard/.local/include
GNURADIO_LIBS = -L/home/woodard/.local/lib64 -lgnuradio-audio -lgnuradio-blocks -lgnuradio-digital -lgnuradio-filter -lgnuradio-fft -lgnuradio-trellis -lgnuradio-runtime -lgnuradio-pmt
HAMLIB_CFLAGS = -I/home/woodard/.local/include
HAMLIB_LIBS = -L/home/woodard/.local/lib -lhamlib
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} '/home/woodard/src/75fasmod/missing' makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = 75fasmod
PACKAGE_BUGREPORT = your.email@example.com
PACKAGE_NAME = 75fasmod
PACKAGE_STRING = 75fasmod 0.1.0
PACKAGE_TARNAME = 75fasmod
PACKAGE_URL = 
PACKAGE_VERSION = 0.1.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /home/woodard/.local/lib/pkgconfig:/home/woodard/.local/lib64/pkgconfig:/home/woodard/.local/lib/pkgconfig:/home/woodard/.local/lib64/pkgconfig:
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.1.0
VOLK_CFLAGS = -I/home/woodard/.local/include
VOLK_LIBS = -L/home/woodard/.local/lib64 -lvolk
abs_builddir = /home/woodard/src/75fasmod
abs_srcdir = /home/woodard/src/75fasmod
abs_top_builddir = /home/woodard/src/75fasmod
abs_top_srcdir = /home/woodard/src/75fasmod
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__rm_f_notfound = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
am__xargs_n = xargs -n
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/woodard/src/75fasmod/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/woodard/.local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
test_frequency_SOURCES = test/test_frequency.cpp src/RadioController.cpp src/THD75.cpp
test_frequency_CPPFLAGS = -I$(top_srcdir)/include $(HAMLIB_CFLAGS) -std=c++20
test_frequency_LDADD = $(HAMLIB_LIBS)
test_power_SOURCES = test/test_power.cpp src/RadioController.cpp src/THD75.cpp
test_power_CPPFLAGS = -I$(top_srcdir)/include $(HAMLIB_CFLAGS) -std=c++20
test_power_LDADD = $(HAMLIB_LIBS)
test_vfo_SOURCES = test/test_vfo.cpp src/RadioController.cpp src/THD75.cpp
test_vfo_CPPFLAGS = -I$(top_srcdir)/include $(HAMLIB_CFLAGS) -std=c++20
test_vfo_LDADD = $(HAMLIB_LIBS)
test_tnc_SOURCES = test/test_tnc.cpp src/RadioController.cpp src/THD75.cpp
test_tnc_CPPFLAGS = -I$(top_srcdir)/include $(HAMLIB_CFLAGS) -std=c++20
test_tnc_LDADD = $(HAMLIB_LIBS)
test_single_dual_SOURCES = test/test_single_dual.cpp src/RadioController.cpp src/THD75.cpp
test_single_dual_CPPFLAGS = -I$(top_srcdir)/include $(HAMLIB_CFLAGS) -std=c++20
test_single_dual_LDADD = $(HAMLIB_LIBS)

# Tell the C++ preprocessor where to find the header files
AM_CPPFLAGS = -I$(top_srcdir)/include

# List all source files from the src/ directory
75fasmod_SOURCES = \
	src/main.cpp \
	src/DataSocket.cpp \
	src/cobs.cpp \
	src/Frame.cpp \
	src/RadioController.cpp \
	src/THD75.cpp \
	src/ModemDSP.cpp \
	src/TcmConfig.cpp


# Feed compiler and linker flags from pkg-config
75fasmod_CXXFLAGS = $(HAMLIB_CFLAGS) $(GNURADIO_CFLAGS) $(FMT_CFLAGS) $(VOLK_CFLAGS) -Wall -Wextra -pthread
75fasmod_LDADD = $(HAMLIB_LIBS) $(GNURADIO_LIBS) $(FMT_LIBS) $(VOLK_LIBS) -lpthread

# Test runner
TESTS = test/run_frequency_test.sh test/run_power_test.sh \
        test/run_vfo_test.sh test/run_tnc_test.sh test/run_single_dual_test.sh

EXTRA_DIST = test/run_frequency_test.sh test/run_power_test.sh \
             test/run_vfo_test.sh test/run_tnc_test.sh \
             test/run_single_dual_test.sh

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .log .o .obj .test .test$(EXEEXT) .trs
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
Doxyfile: $(top_builddir)/config.status $(srcdir)/Doxyfile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && $(am__rm_f) $$files

clean-binPROGRAMS:
	-$(am__rm_f) $(bin_PROGRAMS)

clean-checkPROGRAMS:
	-$(am__rm_f) $(check_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: >>src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: >>src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-DataSocket.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-cobs.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-Frame.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-ModemDSP.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/75fasmod-TcmConfig.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

75fasmod$(EXEEXT): $(75fasmod_OBJECTS) $(75fasmod_DEPENDENCIES) $(EXTRA_75fasmod_DEPENDENCIES) 
	@rm -f 75fasmod$(EXEEXT)
	$(AM_V_CXXLD)$(75fasmod_LINK) $(75fasmod_OBJECTS) $(75fasmod_LDADD) $(LIBS)
test/$(am__dirstamp):
	@$(MKDIR_P) test
	@: >>test/$(am__dirstamp)
test/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) test/$(DEPDIR)
	@: >>test/$(DEPDIR)/$(am__dirstamp)
test/frequency-test_frequency.$(OBJEXT): test/$(am__dirstamp) \
	test/$(DEPDIR)/$(am__dirstamp)
src/test_frequency-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_frequency-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_frequency$(EXEEXT): $(test_frequency_OBJECTS) $(test_frequency_DEPENDENCIES) $(EXTRA_test_frequency_DEPENDENCIES) 
	@rm -f test_frequency$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_frequency_OBJECTS) $(test_frequency_LDADD) $(LIBS)
test/power-test_power.$(OBJEXT): test/$(am__dirstamp) \
	test/$(DEPDIR)/$(am__dirstamp)
src/test_power-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_power-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_power$(EXEEXT): $(test_power_OBJECTS) $(test_power_DEPENDENCIES) $(EXTRA_test_power_DEPENDENCIES) 
	@rm -f test_power$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_power_OBJECTS) $(test_power_LDADD) $(LIBS)
test/single_dual-test_single_dual.$(OBJEXT): test/$(am__dirstamp) \
	test/$(DEPDIR)/$(am__dirstamp)
src/test_single_dual-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_single_dual-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_single_dual$(EXEEXT): $(test_single_dual_OBJECTS) $(test_single_dual_DEPENDENCIES) $(EXTRA_test_single_dual_DEPENDENCIES) 
	@rm -f test_single_dual$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_single_dual_OBJECTS) $(test_single_dual_LDADD) $(LIBS)
test/tnc-test_tnc.$(OBJEXT): test/$(am__dirstamp) \
	test/$(DEPDIR)/$(am__dirstamp)
src/test_tnc-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_tnc-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_tnc$(EXEEXT): $(test_tnc_OBJECTS) $(test_tnc_DEPENDENCIES) $(EXTRA_test_tnc_DEPENDENCIES) 
	@rm -f test_tnc$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_tnc_OBJECTS) $(test_tnc_LDADD) $(LIBS)
test/vfo-test_vfo.$(OBJEXT): test/$(am__dirstamp) \
	test/$(DEPDIR)/$(am__dirstamp)
src/test_vfo-RadioController.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_vfo-THD75.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_vfo$(EXEEXT): $(test_vfo_OBJECTS) $(test_vfo_DEPENDENCIES) $(EXTRA_test_vfo_DEPENDENCIES) 
	@rm -f test_vfo$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_vfo_OBJECTS) $(test_vfo_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f test/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/75fasmod-DataSocket.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-Frame.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-ModemDSP.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-RadioController.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-THD75.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-TcmConfig.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-cobs.Po # am--include-marker
include src/$(DEPDIR)/75fasmod-main.Po # am--include-marker
include src/$(DEPDIR)/test_frequency-RadioController.Po # am--include-marker
include src/$(DEPDIR)/test_frequency-THD75.Po # am--include-marker
include src/$(DEPDIR)/test_power-RadioController.Po # am--include-marker
include src/$(DEPDIR)/test_power-THD75.Po # am--include-marker
include src/$(DEPDIR)/test_single_dual-RadioController.Po # am--include-marker
include src/$(DEPDIR)/test_single_dual-THD75.Po # am--include-marker
include src/$(DEPDIR)/test_tnc-RadioController.Po # am--include-marker
include src/$(DEPDIR)/test_tnc-THD75.Po # am--include-marker
include src/$(DEPDIR)/test_vfo-RadioController.Po # am--include-marker
include src/$(DEPDIR)/test_vfo-THD75.Po # am--include-marker
include test/$(DEPDIR)/frequency-test_frequency.Po # am--include-marker
include test/$(DEPDIR)/power-test_power.Po # am--include-marker
include test/$(DEPDIR)/single_dual-test_single_dual.Po # am--include-marker
include test/$(DEPDIR)/tnc-test_tnc.Po # am--include-marker
include test/$(DEPDIR)/vfo-test_vfo.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@: >>$@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/75fasmod-main.o: src/main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-main.o -MD -MP -MF src/$(DEPDIR)/75fasmod-main.Tpo -c -o src/75fasmod-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-main.Tpo src/$(DEPDIR)/75fasmod-main.Po
#	$(AM_V_CXX)source='src/main.cpp' object='src/75fasmod-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

src/75fasmod-main.obj: src/main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-main.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-main.Tpo -c -o src/75fasmod-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-main.Tpo src/$(DEPDIR)/75fasmod-main.Po
#	$(AM_V_CXX)source='src/main.cpp' object='src/75fasmod-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

src/75fasmod-DataSocket.o: src/DataSocket.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-DataSocket.o -MD -MP -MF src/$(DEPDIR)/75fasmod-DataSocket.Tpo -c -o src/75fasmod-DataSocket.o `test -f 'src/DataSocket.cpp' || echo '$(srcdir)/'`src/DataSocket.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-DataSocket.Tpo src/$(DEPDIR)/75fasmod-DataSocket.Po
#	$(AM_V_CXX)source='src/DataSocket.cpp' object='src/75fasmod-DataSocket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-DataSocket.o `test -f 'src/DataSocket.cpp' || echo '$(srcdir)/'`src/DataSocket.cpp

src/75fasmod-DataSocket.obj: src/DataSocket.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-DataSocket.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-DataSocket.Tpo -c -o src/75fasmod-DataSocket.obj `if test -f 'src/DataSocket.cpp'; then $(CYGPATH_W) 'src/DataSocket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/DataSocket.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-DataSocket.Tpo src/$(DEPDIR)/75fasmod-DataSocket.Po
#	$(AM_V_CXX)source='src/DataSocket.cpp' object='src/75fasmod-DataSocket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-DataSocket.obj `if test -f 'src/DataSocket.cpp'; then $(CYGPATH_W) 'src/DataSocket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/DataSocket.cpp'; fi`

src/75fasmod-cobs.o: src/cobs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-cobs.o -MD -MP -MF src/$(DEPDIR)/75fasmod-cobs.Tpo -c -o src/75fasmod-cobs.o `test -f 'src/cobs.cpp' || echo '$(srcdir)/'`src/cobs.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-cobs.Tpo src/$(DEPDIR)/75fasmod-cobs.Po
#	$(AM_V_CXX)source='src/cobs.cpp' object='src/75fasmod-cobs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-cobs.o `test -f 'src/cobs.cpp' || echo '$(srcdir)/'`src/cobs.cpp

src/75fasmod-cobs.obj: src/cobs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-cobs.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-cobs.Tpo -c -o src/75fasmod-cobs.obj `if test -f 'src/cobs.cpp'; then $(CYGPATH_W) 'src/cobs.cpp'; else $(CYGPATH_W) '$(srcdir)/src/cobs.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-cobs.Tpo src/$(DEPDIR)/75fasmod-cobs.Po
#	$(AM_V_CXX)source='src/cobs.cpp' object='src/75fasmod-cobs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-cobs.obj `if test -f 'src/cobs.cpp'; then $(CYGPATH_W) 'src/cobs.cpp'; else $(CYGPATH_W) '$(srcdir)/src/cobs.cpp'; fi`

src/75fasmod-Frame.o: src/Frame.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-Frame.o -MD -MP -MF src/$(DEPDIR)/75fasmod-Frame.Tpo -c -o src/75fasmod-Frame.o `test -f 'src/Frame.cpp' || echo '$(srcdir)/'`src/Frame.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-Frame.Tpo src/$(DEPDIR)/75fasmod-Frame.Po
#	$(AM_V_CXX)source='src/Frame.cpp' object='src/75fasmod-Frame.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-Frame.o `test -f 'src/Frame.cpp' || echo '$(srcdir)/'`src/Frame.cpp

src/75fasmod-Frame.obj: src/Frame.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-Frame.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-Frame.Tpo -c -o src/75fasmod-Frame.obj `if test -f 'src/Frame.cpp'; then $(CYGPATH_W) 'src/Frame.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Frame.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-Frame.Tpo src/$(DEPDIR)/75fasmod-Frame.Po
#	$(AM_V_CXX)source='src/Frame.cpp' object='src/75fasmod-Frame.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-Frame.obj `if test -f 'src/Frame.cpp'; then $(CYGPATH_W) 'src/Frame.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Frame.cpp'; fi`

src/75fasmod-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-RadioController.o -MD -MP -MF src/$(DEPDIR)/75fasmod-RadioController.Tpo -c -o src/75fasmod-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-RadioController.Tpo src/$(DEPDIR)/75fasmod-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/75fasmod-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/75fasmod-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-RadioController.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-RadioController.Tpo -c -o src/75fasmod-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-RadioController.Tpo src/$(DEPDIR)/75fasmod-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/75fasmod-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/75fasmod-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-THD75.o -MD -MP -MF src/$(DEPDIR)/75fasmod-THD75.Tpo -c -o src/75fasmod-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-THD75.Tpo src/$(DEPDIR)/75fasmod-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/75fasmod-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/75fasmod-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-THD75.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-THD75.Tpo -c -o src/75fasmod-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-THD75.Tpo src/$(DEPDIR)/75fasmod-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/75fasmod-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

src/75fasmod-ModemDSP.o: src/ModemDSP.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-ModemDSP.o -MD -MP -MF src/$(DEPDIR)/75fasmod-ModemDSP.Tpo -c -o src/75fasmod-ModemDSP.o `test -f 'src/ModemDSP.cpp' || echo '$(srcdir)/'`src/ModemDSP.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-ModemDSP.Tpo src/$(DEPDIR)/75fasmod-ModemDSP.Po
#	$(AM_V_CXX)source='src/ModemDSP.cpp' object='src/75fasmod-ModemDSP.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-ModemDSP.o `test -f 'src/ModemDSP.cpp' || echo '$(srcdir)/'`src/ModemDSP.cpp

src/75fasmod-ModemDSP.obj: src/ModemDSP.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-ModemDSP.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-ModemDSP.Tpo -c -o src/75fasmod-ModemDSP.obj `if test -f 'src/ModemDSP.cpp'; then $(CYGPATH_W) 'src/ModemDSP.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ModemDSP.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-ModemDSP.Tpo src/$(DEPDIR)/75fasmod-ModemDSP.Po
#	$(AM_V_CXX)source='src/ModemDSP.cpp' object='src/75fasmod-ModemDSP.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-ModemDSP.obj `if test -f 'src/ModemDSP.cpp'; then $(CYGPATH_W) 'src/ModemDSP.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ModemDSP.cpp'; fi`

src/75fasmod-TcmConfig.o: src/TcmConfig.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-TcmConfig.o -MD -MP -MF src/$(DEPDIR)/75fasmod-TcmConfig.Tpo -c -o src/75fasmod-TcmConfig.o `test -f 'src/TcmConfig.cpp' || echo '$(srcdir)/'`src/TcmConfig.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-TcmConfig.Tpo src/$(DEPDIR)/75fasmod-TcmConfig.Po
#	$(AM_V_CXX)source='src/TcmConfig.cpp' object='src/75fasmod-TcmConfig.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-TcmConfig.o `test -f 'src/TcmConfig.cpp' || echo '$(srcdir)/'`src/TcmConfig.cpp

src/75fasmod-TcmConfig.obj: src/TcmConfig.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -MT src/75fasmod-TcmConfig.obj -MD -MP -MF src/$(DEPDIR)/75fasmod-TcmConfig.Tpo -c -o src/75fasmod-TcmConfig.obj `if test -f 'src/TcmConfig.cpp'; then $(CYGPATH_W) 'src/TcmConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/TcmConfig.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/75fasmod-TcmConfig.Tpo src/$(DEPDIR)/75fasmod-TcmConfig.Po
#	$(AM_V_CXX)source='src/TcmConfig.cpp' object='src/75fasmod-TcmConfig.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(75fasmod_CXXFLAGS) $(CXXFLAGS) -c -o src/75fasmod-TcmConfig.obj `if test -f 'src/TcmConfig.cpp'; then $(CYGPATH_W) 'src/TcmConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/TcmConfig.cpp'; fi`

test/frequency-test_frequency.o: test/test_frequency.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/frequency-test_frequency.o -MD -MP -MF test/$(DEPDIR)/frequency-test_frequency.Tpo -c -o test/frequency-test_frequency.o `test -f 'test/test_frequency.cpp' || echo '$(srcdir)/'`test/test_frequency.cpp
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/frequency-test_frequency.Tpo test/$(DEPDIR)/frequency-test_frequency.Po
#	$(AM_V_CXX)source='test/test_frequency.cpp' object='test/frequency-test_frequency.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/frequency-test_frequency.o `test -f 'test/test_frequency.cpp' || echo '$(srcdir)/'`test/test_frequency.cpp

test/frequency-test_frequency.obj: test/test_frequency.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/frequency-test_frequency.obj -MD -MP -MF test/$(DEPDIR)/frequency-test_frequency.Tpo -c -o test/frequency-test_frequency.obj `if test -f 'test/test_frequency.cpp'; then $(CYGPATH_W) 'test/test_frequency.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_frequency.cpp'; fi`
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/frequency-test_frequency.Tpo test/$(DEPDIR)/frequency-test_frequency.Po
#	$(AM_V_CXX)source='test/test_frequency.cpp' object='test/frequency-test_frequency.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/frequency-test_frequency.obj `if test -f 'test/test_frequency.cpp'; then $(CYGPATH_W) 'test/test_frequency.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_frequency.cpp'; fi`

src/test_frequency-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_frequency-RadioController.o -MD -MP -MF src/$(DEPDIR)/test_frequency-RadioController.Tpo -c -o src/test_frequency-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_frequency-RadioController.Tpo src/$(DEPDIR)/test_frequency-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_frequency-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_frequency-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/test_frequency-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_frequency-RadioController.obj -MD -MP -MF src/$(DEPDIR)/test_frequency-RadioController.Tpo -c -o src/test_frequency-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_frequency-RadioController.Tpo src/$(DEPDIR)/test_frequency-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_frequency-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_frequency-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/test_frequency-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_frequency-THD75.o -MD -MP -MF src/$(DEPDIR)/test_frequency-THD75.Tpo -c -o src/test_frequency-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_frequency-THD75.Tpo src/$(DEPDIR)/test_frequency-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_frequency-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_frequency-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/test_frequency-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_frequency-THD75.obj -MD -MP -MF src/$(DEPDIR)/test_frequency-THD75.Tpo -c -o src/test_frequency-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_frequency-THD75.Tpo src/$(DEPDIR)/test_frequency-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_frequency-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_frequency_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_frequency-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

test/power-test_power.o: test/test_power.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/power-test_power.o -MD -MP -MF test/$(DEPDIR)/power-test_power.Tpo -c -o test/power-test_power.o `test -f 'test/test_power.cpp' || echo '$(srcdir)/'`test/test_power.cpp
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/power-test_power.Tpo test/$(DEPDIR)/power-test_power.Po
#	$(AM_V_CXX)source='test/test_power.cpp' object='test/power-test_power.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/power-test_power.o `test -f 'test/test_power.cpp' || echo '$(srcdir)/'`test/test_power.cpp

test/power-test_power.obj: test/test_power.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/power-test_power.obj -MD -MP -MF test/$(DEPDIR)/power-test_power.Tpo -c -o test/power-test_power.obj `if test -f 'test/test_power.cpp'; then $(CYGPATH_W) 'test/test_power.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_power.cpp'; fi`
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/power-test_power.Tpo test/$(DEPDIR)/power-test_power.Po
#	$(AM_V_CXX)source='test/test_power.cpp' object='test/power-test_power.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/power-test_power.obj `if test -f 'test/test_power.cpp'; then $(CYGPATH_W) 'test/test_power.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_power.cpp'; fi`

src/test_power-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_power-RadioController.o -MD -MP -MF src/$(DEPDIR)/test_power-RadioController.Tpo -c -o src/test_power-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_power-RadioController.Tpo src/$(DEPDIR)/test_power-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_power-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_power-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/test_power-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_power-RadioController.obj -MD -MP -MF src/$(DEPDIR)/test_power-RadioController.Tpo -c -o src/test_power-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_power-RadioController.Tpo src/$(DEPDIR)/test_power-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_power-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_power-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/test_power-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_power-THD75.o -MD -MP -MF src/$(DEPDIR)/test_power-THD75.Tpo -c -o src/test_power-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_power-THD75.Tpo src/$(DEPDIR)/test_power-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_power-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_power-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/test_power-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_power-THD75.obj -MD -MP -MF src/$(DEPDIR)/test_power-THD75.Tpo -c -o src/test_power-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_power-THD75.Tpo src/$(DEPDIR)/test_power-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_power-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_power_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_power-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

test/single_dual-test_single_dual.o: test/test_single_dual.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/single_dual-test_single_dual.o -MD -MP -MF test/$(DEPDIR)/single_dual-test_single_dual.Tpo -c -o test/single_dual-test_single_dual.o `test -f 'test/test_single_dual.cpp' || echo '$(srcdir)/'`test/test_single_dual.cpp
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/single_dual-test_single_dual.Tpo test/$(DEPDIR)/single_dual-test_single_dual.Po
#	$(AM_V_CXX)source='test/test_single_dual.cpp' object='test/single_dual-test_single_dual.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/single_dual-test_single_dual.o `test -f 'test/test_single_dual.cpp' || echo '$(srcdir)/'`test/test_single_dual.cpp

test/single_dual-test_single_dual.obj: test/test_single_dual.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/single_dual-test_single_dual.obj -MD -MP -MF test/$(DEPDIR)/single_dual-test_single_dual.Tpo -c -o test/single_dual-test_single_dual.obj `if test -f 'test/test_single_dual.cpp'; then $(CYGPATH_W) 'test/test_single_dual.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_single_dual.cpp'; fi`
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/single_dual-test_single_dual.Tpo test/$(DEPDIR)/single_dual-test_single_dual.Po
#	$(AM_V_CXX)source='test/test_single_dual.cpp' object='test/single_dual-test_single_dual.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/single_dual-test_single_dual.obj `if test -f 'test/test_single_dual.cpp'; then $(CYGPATH_W) 'test/test_single_dual.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_single_dual.cpp'; fi`

src/test_single_dual-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_single_dual-RadioController.o -MD -MP -MF src/$(DEPDIR)/test_single_dual-RadioController.Tpo -c -o src/test_single_dual-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_single_dual-RadioController.Tpo src/$(DEPDIR)/test_single_dual-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_single_dual-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_single_dual-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/test_single_dual-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_single_dual-RadioController.obj -MD -MP -MF src/$(DEPDIR)/test_single_dual-RadioController.Tpo -c -o src/test_single_dual-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_single_dual-RadioController.Tpo src/$(DEPDIR)/test_single_dual-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_single_dual-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_single_dual-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/test_single_dual-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_single_dual-THD75.o -MD -MP -MF src/$(DEPDIR)/test_single_dual-THD75.Tpo -c -o src/test_single_dual-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_single_dual-THD75.Tpo src/$(DEPDIR)/test_single_dual-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_single_dual-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_single_dual-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/test_single_dual-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_single_dual-THD75.obj -MD -MP -MF src/$(DEPDIR)/test_single_dual-THD75.Tpo -c -o src/test_single_dual-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_single_dual-THD75.Tpo src/$(DEPDIR)/test_single_dual-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_single_dual-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_single_dual_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_single_dual-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

test/tnc-test_tnc.o: test/test_tnc.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/tnc-test_tnc.o -MD -MP -MF test/$(DEPDIR)/tnc-test_tnc.Tpo -c -o test/tnc-test_tnc.o `test -f 'test/test_tnc.cpp' || echo '$(srcdir)/'`test/test_tnc.cpp
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/tnc-test_tnc.Tpo test/$(DEPDIR)/tnc-test_tnc.Po
#	$(AM_V_CXX)source='test/test_tnc.cpp' object='test/tnc-test_tnc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/tnc-test_tnc.o `test -f 'test/test_tnc.cpp' || echo '$(srcdir)/'`test/test_tnc.cpp

test/tnc-test_tnc.obj: test/test_tnc.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/tnc-test_tnc.obj -MD -MP -MF test/$(DEPDIR)/tnc-test_tnc.Tpo -c -o test/tnc-test_tnc.obj `if test -f 'test/test_tnc.cpp'; then $(CYGPATH_W) 'test/test_tnc.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_tnc.cpp'; fi`
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/tnc-test_tnc.Tpo test/$(DEPDIR)/tnc-test_tnc.Po
#	$(AM_V_CXX)source='test/test_tnc.cpp' object='test/tnc-test_tnc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/tnc-test_tnc.obj `if test -f 'test/test_tnc.cpp'; then $(CYGPATH_W) 'test/test_tnc.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_tnc.cpp'; fi`

src/test_tnc-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_tnc-RadioController.o -MD -MP -MF src/$(DEPDIR)/test_tnc-RadioController.Tpo -c -o src/test_tnc-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_tnc-RadioController.Tpo src/$(DEPDIR)/test_tnc-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_tnc-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_tnc-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/test_tnc-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_tnc-RadioController.obj -MD -MP -MF src/$(DEPDIR)/test_tnc-RadioController.Tpo -c -o src/test_tnc-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_tnc-RadioController.Tpo src/$(DEPDIR)/test_tnc-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_tnc-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_tnc-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/test_tnc-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_tnc-THD75.o -MD -MP -MF src/$(DEPDIR)/test_tnc-THD75.Tpo -c -o src/test_tnc-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_tnc-THD75.Tpo src/$(DEPDIR)/test_tnc-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_tnc-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_tnc-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/test_tnc-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_tnc-THD75.obj -MD -MP -MF src/$(DEPDIR)/test_tnc-THD75.Tpo -c -o src/test_tnc-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_tnc-THD75.Tpo src/$(DEPDIR)/test_tnc-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_tnc-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_tnc_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_tnc-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

test/vfo-test_vfo.o: test/test_vfo.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/vfo-test_vfo.o -MD -MP -MF test/$(DEPDIR)/vfo-test_vfo.Tpo -c -o test/vfo-test_vfo.o `test -f 'test/test_vfo.cpp' || echo '$(srcdir)/'`test/test_vfo.cpp
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/vfo-test_vfo.Tpo test/$(DEPDIR)/vfo-test_vfo.Po
#	$(AM_V_CXX)source='test/test_vfo.cpp' object='test/vfo-test_vfo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/vfo-test_vfo.o `test -f 'test/test_vfo.cpp' || echo '$(srcdir)/'`test/test_vfo.cpp

test/vfo-test_vfo.obj: test/test_vfo.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT test/vfo-test_vfo.obj -MD -MP -MF test/$(DEPDIR)/vfo-test_vfo.Tpo -c -o test/vfo-test_vfo.obj `if test -f 'test/test_vfo.cpp'; then $(CYGPATH_W) 'test/test_vfo.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_vfo.cpp'; fi`
	$(AM_V_at)$(am__mv) test/$(DEPDIR)/vfo-test_vfo.Tpo test/$(DEPDIR)/vfo-test_vfo.Po
#	$(AM_V_CXX)source='test/test_vfo.cpp' object='test/vfo-test_vfo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o test/vfo-test_vfo.obj `if test -f 'test/test_vfo.cpp'; then $(CYGPATH_W) 'test/test_vfo.cpp'; else $(CYGPATH_W) '$(srcdir)/test/test_vfo.cpp'; fi`

src/test_vfo-RadioController.o: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_vfo-RadioController.o -MD -MP -MF src/$(DEPDIR)/test_vfo-RadioController.Tpo -c -o src/test_vfo-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_vfo-RadioController.Tpo src/$(DEPDIR)/test_vfo-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_vfo-RadioController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_vfo-RadioController.o `test -f 'src/RadioController.cpp' || echo '$(srcdir)/'`src/RadioController.cpp

src/test_vfo-RadioController.obj: src/RadioController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_vfo-RadioController.obj -MD -MP -MF src/$(DEPDIR)/test_vfo-RadioController.Tpo -c -o src/test_vfo-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_vfo-RadioController.Tpo src/$(DEPDIR)/test_vfo-RadioController.Po
#	$(AM_V_CXX)source='src/RadioController.cpp' object='src/test_vfo-RadioController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_vfo-RadioController.obj `if test -f 'src/RadioController.cpp'; then $(CYGPATH_W) 'src/RadioController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RadioController.cpp'; fi`

src/test_vfo-THD75.o: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_vfo-THD75.o -MD -MP -MF src/$(DEPDIR)/test_vfo-THD75.Tpo -c -o src/test_vfo-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_vfo-THD75.Tpo src/$(DEPDIR)/test_vfo-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_vfo-THD75.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_vfo-THD75.o `test -f 'src/THD75.cpp' || echo '$(srcdir)/'`src/THD75.cpp

src/test_vfo-THD75.obj: src/THD75.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/test_vfo-THD75.obj -MD -MP -MF src/$(DEPDIR)/test_vfo-THD75.Tpo -c -o src/test_vfo-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_vfo-THD75.Tpo src/$(DEPDIR)/test_vfo-THD75.Po
#	$(AM_V_CXX)source='src/THD75.cpp' object='src/test_vfo-THD75.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_vfo_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/test_vfo-THD75.obj `if test -f 'src/THD75.cpp'; then $(CYGPATH_W) 'src/THD75.cpp'; else $(CYGPATH_W) '$(srcdir)/src/THD75.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

# Recover from deleted '.trs' file; this should ensure that
# "rm -f foo.log; make foo.trs" re-run 'foo.test', and re-create
# both 'foo.log' and 'foo.trs'.  Break the recipe in two subshells
# to avoid problems with "make -n".
.log.trs:
	rm -f $< $@
	$(MAKE) $(AM_MAKEFLAGS) $<

# Leading 'am--fnord' is there to ensure the list of targets does not
# expand to empty, as could happen e.g. with make check TESTS=''.
am--fnord $(TEST_LOGS) $(TEST_LOGS:.log=.trs): $(am__force_recheck)
am--force-recheck:
	@:
$(TEST_SUITE_LOG): $(TEST_LOGS)
	@$(am__set_TESTS_bases); \
	am__f_ok () { test -f "$$1" && test -r "$$1"; }; \
	redo_bases=`for i in $$bases; do \
	              am__f_ok $$i.trs && am__f_ok $$i.log || echo $$i; \
	            done`; \
	if test -n "$$redo_bases"; then \
	  redo_logs=`for i in $$redo_bases; do echo $$i.log; done`; \
	  redo_results=`for i in $$redo_bases; do echo $$i.trs; done`; \
	  if $(am__make_dryrun); then :; else \
	    rm -f $$redo_logs && rm -f $$redo_results || exit 1; \
	  fi; \
	fi; \
	if test -n "$$am__remaking_logs"; then \
	  echo "fatal: making $(TEST_SUITE_LOG): possible infinite" \
	       "recursion detected" >&2; \
	elif test -n "$$redo_logs"; then \
	  am__remaking_logs=yes $(MAKE) $(AM_MAKEFLAGS) $$redo_logs; \
	fi; \
	if $(am__make_dryrun); then :; else \
	  st=0;  \
	  errmsg="fatal: making $(TEST_SUITE_LOG): failed to create"; \
	  for i in $$redo_bases; do \
	    test -f $$i.trs && test -r $$i.trs \
	      || { echo "$$errmsg $$i.trs" >&2; st=1; }; \
	    test -f $$i.log && test -r $$i.log \
	      || { echo "$$errmsg $$i.log" >&2; st=1; }; \
	  done; \
	  test $$st -eq 0 || exit 1; \
	fi
	@$(am__sh_e_setup); $(am__tty_colors); $(am__set_TESTS_bases); \
	ws='[ 	]'; \
	results=`for b in $$bases; do echo $$b.trs; done`; \
	test -n "$$results" || results=/dev/null; \
	all=`  grep "^$$ws*:test-result:"           $$results | wc -l`; \
	pass=` grep "^$$ws*:test-result:$$ws*PASS"  $$results | wc -l`; \
	fail=` grep "^$$ws*:test-result:$$ws*FAIL"  $$results | wc -l`; \
	skip=` grep "^$$ws*:test-result:$$ws*SKIP"  $$results | wc -l`; \
	xfail=`grep "^$$ws*:test-result:$$ws*XFAIL" $$results | wc -l`; \
	xpass=`grep "^$$ws*:test-result:$$ws*XPASS" $$results | wc -l`; \
	error=`grep "^$$ws*:test-result:$$ws*ERROR" $$results | wc -l`; \
	if test `expr $$fail + $$xpass + $$error` -eq 0; then \
	  success=true; \
	else \
	  success=false; \
	fi; \
	br='==================='; br=$$br$$br$$br$$br; \
	result_count () \
	{ \
	    if test x"$$1" = x"--maybe-color"; then \
	      maybe_colorize=yes; \
	    elif test x"$$1" = x"--no-color"; then \
	      maybe_colorize=no; \
	    else \
	      echo "$@: invalid 'result_count' usage" >&2; exit 4; \
	    fi; \
	    shift; \
	    desc=$$1 count=$$2; \
	    if test $$maybe_colorize = yes && test $$count -gt 0; then \
	      color_start=$$3 color_end=$$std; \
	    else \
	      color_start= color_end=; \
	    fi; \
	    echo "$${color_start}# $$desc $$count$${color_end}"; \
	}; \
	create_testsuite_report () \
	{ \
	  result_count $$1 "TOTAL:" $$all   "$$brg"; \
	  result_count $$1 "PASS: " $$pass  "$$grn"; \
	  result_count $$1 "SKIP: " $$skip  "$$blu"; \
	  result_count $$1 "XFAIL:" $$xfail "$$lgn"; \
	  result_count $$1 "FAIL: " $$fail  "$$red"; \
	  result_count $$1 "XPASS:" $$xpass "$$red"; \
	  result_count $$1 "ERROR:" $$error "$$mgn"; \
	}; \
	output_system_information () \
	{ \
          echo;                                     \
	  { uname -a | $(AWK) '{                    \
  printf "System information (uname -a):";          \
  for (i = 1; i < NF; ++i)                          \
    {                                               \
      if (i != 2)                                   \
        printf " %s", $$i;                          \
    }                                               \
  printf "\n";                                      \
}'; } 2>&1;                                         \
	  if test -r /etc/os-release; then          \
	    echo "Distribution information (/etc/os-release):"; \
	    sed 8q /etc/os-release;                 \
	  elif test -r /etc/issue; then             \
	    echo "Distribution information (/etc/issue):";      \
	    cat /etc/issue;                         \
	  fi;                                       \
	}; \
	please_report () \
	{ \
echo "Some test(s) failed.  Please report this to $(PACKAGE_BUGREPORT),";    \
echo "together with the test-suite.log file (gzipped) and your system";      \
echo "information.  Thanks.";                                                \
	}; \
	{								\
	  echo "$(PACKAGE_STRING): $(subdir)/$(TEST_SUITE_LOG)" |	\
	    $(am__rst_title);						\
	  create_testsuite_report --no-color;				\
	  output_system_information;                                    \
	  echo;								\
	  echo ".. contents:: :depth: 2";				\
	  echo;								\
	  for b in $$bases; do echo $$b; done				\
	    | $(am__create_global_log);					\
	} >$(TEST_SUITE_LOG).tmp || exit 1;				\
	mv $(TEST_SUITE_LOG).tmp $(TEST_SUITE_LOG);			\
	if $$success; then						\
	  col="$$grn";							\
	 else								\
	  col="$$red";							\
	  test x"$$VERBOSE" = x || cat $(TEST_SUITE_LOG);		\
	fi;								\
	echo "$${col}$$br$${std}"; 					\
	echo "$${col}Testsuite summary"$(AM_TESTSUITE_SUMMARY_HEADER)"$${std}";	\
	echo "$${col}$$br$${std}"; 					\
	create_testsuite_report --maybe-color;				\
	echo "$$col$$br$$std";						\
	if $$success; then :; else					\
	  echo "$${col}See $(subdir)/$(TEST_SUITE_LOG) for debugging.$${std}";\
	  if test -n "$(PACKAGE_BUGREPORT)"; then			\
	    please_report | sed -e "s/^/$${col}/" -e s/'$$'/"$${std}"/; \
	  fi;								\
	  echo "$$col$$br$$std";					\
	fi;								\
	$$success || exit 1

check-TESTS: $(check_PROGRAMS)
	@$(am__rm_f) $(RECHECK_LOGS)
	@$(am__rm_f) $(RECHECK_LOGS:.log=.trs)
	@$(am__rm_f) $(TEST_SUITE_LOG)
	@set +e; $(am__set_TESTS_bases); \
	log_list=`for i in $$bases; do echo $$i.log; done`; \
	log_list=`echo $$log_list`; \
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) TEST_LOGS="$$log_list"; \
	exit $$?;
recheck: all $(check_PROGRAMS)
	@$(am__rm_f) $(TEST_SUITE_LOG)
	@set +e; $(am__set_TESTS_bases); \
	bases=`for i in $$bases; do echo $$i; done \
	         | $(am__list_recheck_tests)` || exit 1; \
	log_list=`for i in $$bases; do echo $$i.log; done`; \
	log_list=`echo $$log_list`; \
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) \
	        am__force_recheck=am--force-recheck \
	        TEST_LOGS="$$log_list"; \
	exit $$?
test/run_frequency_test.sh.log: test/run_frequency_test.sh
	@p='test/run_frequency_test.sh'; \
	b='test/run_frequency_test.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
test/run_power_test.sh.log: test/run_power_test.sh
	@p='test/run_power_test.sh'; \
	b='test/run_power_test.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
test/run_vfo_test.sh.log: test/run_vfo_test.sh
	@p='test/run_vfo_test.sh'; \
	b='test/run_vfo_test.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
test/run_tnc_test.sh.log: test/run_tnc_test.sh
	@p='test/run_tnc_test.sh'; \
	b='test/run_tnc_test.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
test/run_single_dual_test.sh.log: test/run_single_dual_test.sh
	@p='test/run_single_dual_test.sh'; \
	b='test/run_single_dual_test.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
.test.log:
	@p='$<'; \
	$(am__set_b); \
	$(am__check_pre) $(TEST_LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_TEST_LOG_DRIVER_FLAGS) $(TEST_LOG_DRIVER_FLAGS) -- $(TEST_LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
#.test$(EXEEXT).log:
#	@p='$<'; \
#	$(am__set_b); \
#	$(am__check_pre) $(TEST_LOG_DRIVER) --test-name "$$f" \
#	--log-file $$b.log --trs-file $$b.trs \
#	$(am__common_driver_flags) $(AM_TEST_LOG_DRIVER_FLAGS) $(TEST_LOG_DRIVER_FLAGS) -- $(TEST_LOG_COMPILE) \
#	"$$tst" $(AM_TESTS_FD_REDIRECT)

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	$(AM_V_at)$(MKDIR_P) "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-bzip3: distdir
	tardir=$(distdir) && $(am__tar) | bzip3 -c >$(distdir).tar.bz3
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.bz3*) \
	  bzip3 -dc $(distdir).tar.bz3 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-$(am__rm_f) $(TEST_LOGS)
	-$(am__rm_f) $(TEST_LOGS:.log=.trs)
	-$(am__rm_f) $(TEST_SUITE_LOG)

clean-generic:

distclean-generic:
	-$(am__rm_f) $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || $(am__rm_f) $(CONFIG_CLEAN_VPATH_FILES)
	-$(am__rm_f) src/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) src/$(am__dirstamp)
	-$(am__rm_f) test/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) test/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f src/$(DEPDIR)/75fasmod-DataSocket.Po
	-rm -f src/$(DEPDIR)/75fasmod-Frame.Po
	-rm -f src/$(DEPDIR)/75fasmod-ModemDSP.Po
	-rm -f src/$(DEPDIR)/75fasmod-RadioController.Po
	-rm -f src/$(DEPDIR)/75fasmod-THD75.Po
	-rm -f src/$(DEPDIR)/75fasmod-TcmConfig.Po
	-rm -f src/$(DEPDIR)/75fasmod-cobs.Po
	-rm -f src/$(DEPDIR)/75fasmod-main.Po
	-rm -f src/$(DEPDIR)/test_frequency-RadioController.Po
	-rm -f src/$(DEPDIR)/test_frequency-THD75.Po
	-rm -f src/$(DEPDIR)/test_power-RadioController.Po
	-rm -f src/$(DEPDIR)/test_power-THD75.Po
	-rm -f src/$(DEPDIR)/test_single_dual-RadioController.Po
	-rm -f src/$(DEPDIR)/test_single_dual-THD75.Po
	-rm -f src/$(DEPDIR)/test_tnc-RadioController.Po
	-rm -f src/$(DEPDIR)/test_tnc-THD75.Po
	-rm -f src/$(DEPDIR)/test_vfo-RadioController.Po
	-rm -f src/$(DEPDIR)/test_vfo-THD75.Po
	-rm -f test/$(DEPDIR)/frequency-test_frequency.Po
	-rm -f test/$(DEPDIR)/power-test_power.Po
	-rm -f test/$(DEPDIR)/single_dual-test_single_dual.Po
	-rm -f test/$(DEPDIR)/tnc-test_tnc.Po
	-rm -f test/$(DEPDIR)/vfo-test_vfo.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f src/$(DEPDIR)/75fasmod-DataSocket.Po
	-rm -f src/$(DEPDIR)/75fasmod-Frame.Po
	-rm -f src/$(DEPDIR)/75fasmod-ModemDSP.Po
	-rm -f src/$(DEPDIR)/75fasmod-RadioController.Po
	-rm -f src/$(DEPDIR)/75fasmod-THD75.Po
	-rm -f src/$(DEPDIR)/75fasmod-TcmConfig.Po
	-rm -f src/$(DEPDIR)/75fasmod-cobs.Po
	-rm -f src/$(DEPDIR)/75fasmod-main.Po
	-rm -f src/$(DEPDIR)/test_frequency-RadioController.Po
	-rm -f src/$(DEPDIR)/test_frequency-THD75.Po
	-rm -f src/$(DEPDIR)/test_power-RadioController.Po
	-rm -f src/$(DEPDIR)/test_power-THD75.Po
	-rm -f src/$(DEPDIR)/test_single_dual-RadioController.Po
	-rm -f src/$(DEPDIR)/test_single_dual-THD75.Po
	-rm -f src/$(DEPDIR)/test_tnc-RadioController.Po
	-rm -f src/$(DEPDIR)/test_tnc-THD75.Po
	-rm -f src/$(DEPDIR)/test_vfo-RadioController.Po
	-rm -f src/$(DEPDIR)/test_vfo-THD75.Po
	-rm -f test/$(DEPDIR)/frequency-test_frequency.Po
	-rm -f test/$(DEPDIR)/power-test_power.Po
	-rm -f test/$(DEPDIR)/single_dual-test_single_dual.Po
	-rm -f test/$(DEPDIR)/tnc-test_tnc.Po
	-rm -f test/$(DEPDIR)/vfo-test_vfo.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: check-am install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-TESTS check-am clean clean-binPROGRAMS \
	clean-checkPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-bzip3 dist-gzip dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am recheck tags tags-am \
	uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Documentation targets
.PHONY: docs
docs: Doxyfile
	doxygen Doxyfile

.PHONY: clean-docs
clean-docs:
	rm -rf docs/html docs/latex

.PHONY: install-docs
install-docs: docs

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

# Tell GNU make to disable its built-in pattern rules.
%:: %,v
%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
