#!/usr/bin/env bash
set -euo pipefail

# Navigate to project root relative to script path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

EXIT_CODE=0

echo "=== 1. Checking Code Formatting (clang-format) ==="
SRC_FILES=$(find src include -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.cc" -o -name "*.hh" \) 2>/dev/null || true)

if [ -n "$SRC_FILES" ]; then
    if ! clang-format --dry-run -Werror $SRC_FILES 2>&1; then
        echo "❌ Formatting issues found. Fix using: clang-format -i <file>"
        EXIT_CODE=1
    else
        echo "✅ Code formatting check passed."
    fi
else
    echo "⚠️ No C/C++ source files found for formatting."
fi

echo ""
echo "=== 2. Running Static Analysis (clang-tidy) ==="

# Locate compilation database generated by bear
COMPDB_DIR=""
if [ -f "compile_commands.json" ]; then
    COMPDB_DIR="."
elif [ -f "build/compile_commands.json" ]; then
    COMPDB_DIR="build"
fi

if [ -z "$COMPDB_DIR" ]; then
    echo "❌ Error: compile_commands.json not found."
    echo "👉 Please run your build with bear first (e.g., 'bear -- make -C build')."
    exit 1
fi

# Determine available clang-tidy runner (parallel runner preferred)
TIDY_RUNNER=""
if command -v run-clang-tidy >/dev/null 2>&1; then
    TIDY_RUNNER="run-clang-tidy"
elif command -v run-clang-tidy.py >/dev/null 2>&1; then
    TIDY_RUNNER="run-clang-tidy.py"
fi

# Match only header files inside project src and include directories
HEADER_FILTER="^${PROJECT_ROOT}/(src|include)/.*|.*/(src|include)/.*"

if [ -n "$TIDY_RUNNER" ]; then
    # Run clang-tidy in parallel across project files in compilation database
    # Note: External headers are excluded, but compiler errors in those headers
    # may still appear. Use -extra-arg to mark external paths as system headers.
    echo "Running clang-tidy with external header exclusion..."
    if ! "$TIDY_RUNNER" -p "$COMPDB_DIR" -header-filter="$HEADER_FILTER" -exclude-header-filter=".*(\.local|/usr/).*" -quiet '.*(src|include)/.*' 2>&1 | head -100; then
        echo "..."
        echo "❌ Clang-tidy static analysis issues detected."
        EXIT_CODE=1
    else
        echo "✅ Clang-tidy static analysis passed."
    fi
else
    # Fallback to direct clang-tidy execution on each source file
    echo "ℹ️ run-clang-tidy not found; executing clang-tidy sequentially..."
    TIDY_FAILED=0
    for file in $SRC_FILES; do
        if [[ "$file" =~ \.(cpp|cc|cxx|c)$ ]]; then
            if ! clang-tidy -p "$COMPDB_DIR" -header-filter="$HEADER_FILTER" -exclude-header-filter=".*(\.local|/usr/).*" "$file" --quiet 2>&1 | grep -v "^Error while processing" | head -50; then
                TIDY_FAILED=1
            fi
        fi
    done

    if [ $TIDY_FAILED -ne 0 ]; then
        echo "❌ Clang-tidy static analysis issues detected."
        EXIT_CODE=1
    else
        echo "✅ Clang-tidy static analysis passed."
    fi
fi

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "❌ Linter suite failed."
    exit 1
fi

echo ""
echo "✅ All lint checks passed successfully!"
exit 0
